[package]
name = "haste_protos"
version = "0.0.0"
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
prost.workspace = true

[build-dependencies]
prost-build.workspace = true
protobuf-src.workspace = true

[features]
dota2 = []
